codecov:
  require_ci_to_pass: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        # The chat module contains WebSocket handlers and streaming logic
        # that requires a live CLI subprocess and WS connections.
        # Unit tests cover the testable business logic but cannot cover
        # infrastructure code (ws_chat_handler.rs, stream_response internals).
        target: 30%
        threshold: 5%

ignore:
  # Desktop Tauri app — separate crate, not compiled by cargo llvm-cov
  - "desktop/**"
  # Chat infrastructure — requires live CLI subprocess, WS connections, and
  # streaming pipelines. Business logic is tested via mock-based unit tests
  # but the send/stream/persist pipeline is integration-only.
  - "src/api/ws_chat_handler.rs"
  - "src/api/chat_handlers.rs"
  - "src/chat/**"
  # Neo4j client — all methods require a running Neo4j instance.
  # Tested by integration tests (ci.yml: integration-tests, api-tests jobs).
  # Unit tests use MockGraphStore (mock.rs) which is fully covered.
  - "src/neo4j/client.rs"
  # Pure trait→client delegation — untestable without Neo4j, zero logic.
  - "src/neo4j/impl_graph_store.rs"
  # Main entry points
  - "src/main.rs"
  - "src/bin/**"
