codecov:
  require_ci_to_pass: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        # The chat module contains WebSocket handlers and streaming logic
        # that requires a live CLI subprocess and WS connections.
        # Unit tests cover the testable business logic but cannot cover
        # infrastructure code (ws_chat_handler.rs, stream_response internals).
        target: 30%
        threshold: 5%

ignore:
  # Desktop Tauri app — separate crate, not compiled by cargo llvm-cov
  - "desktop/**"
  # Chat infrastructure — requires live CLI subprocess, WS connections, and
  # streaming pipelines. Business logic is tested via mock-based unit tests
  # but the send/stream/persist pipeline is integration-only.
  - "src/api/ws_chat_handler.rs"
  - "src/api/chat_handlers.rs"
  - "src/chat/**"
  # Main entry points
  - "src/main.rs"
  - "src/bin/**"
