//! Community label enrichment via LLM.
//!
//! Provides a [`CommunityEnricher`] trait for replacing heuristic community
//! labels (longest common path prefix) with semantically meaningful labels
//! generated by an LLM.
//!
//! Two implementations:
//! - [`NoopCommunityEnricher`] — returns labels unchanged (default, no LLM)
//! - [`LlmCommunityEnricher`] — batches communities (5 per prompt) and calls
//!   an OpenAI-compatible LLM endpoint. Falls back to heuristic on failure.

use anyhow::Result;
use async_trait::async_trait;
use std::collections::HashMap;

use super::models::{CodeGraph, CommunityInfo, NodeMetrics};

// ============================================================================
// Trait
// ============================================================================

/// Trait for enriching community labels after Louvain detection.
///
/// Implementations receive the full community list plus graph context
/// (for selecting representative members) and mutate labels in-place.
#[async_trait]
pub trait CommunityEnricher: Send + Sync {
    /// Enrich community labels in-place.
    ///
    /// Implementations should:
    /// 1. Select top members per community (by PageRank)
    /// 2. Generate a short semantic label (2-4 words)
    /// 3. Set `community.enriched_by` to "llm" or "heuristic"
    async fn enrich_labels(
        &self,
        communities: &mut [CommunityInfo],
        graph: &CodeGraph,
        metrics: &HashMap<String, NodeMetrics>,
    ) -> Result<()>;
}

// ============================================================================
// NoopCommunityEnricher — passthrough (no LLM)
// ============================================================================

/// No-op enricher that leaves labels unchanged.
///
/// Used when no LLM is configured, or in tests.
pub struct NoopCommunityEnricher;

#[async_trait]
impl CommunityEnricher for NoopCommunityEnricher {
    async fn enrich_labels(
        &self,
        communities: &mut [CommunityInfo],
        _graph: &CodeGraph,
        _metrics: &HashMap<String, NodeMetrics>,
    ) -> Result<()> {
        // Labels remain as-is (heuristic), enriched_by stays "heuristic"
        for community in communities.iter_mut() {
            if community.enriched_by.is_none() {
                community.enriched_by = Some("heuristic".to_string());
            }
        }
        Ok(())
    }
}

// ============================================================================
// LlmCommunityEnricher — batch LLM enrichment
// ============================================================================

/// LLM-backed community enricher.
///
/// Sends batches of 5 communities to an OpenAI-compatible chat endpoint,
/// extracts JSON labels from the response, and falls back to heuristic
/// labels on any failure.
pub struct LlmCommunityEnricher {
    /// HTTP client
    client: reqwest::Client,
    /// LLM API base URL (e.g. "https://api.openai.com/v1")
    api_base: String,
    /// API key for authentication
    api_key: String,
    /// Model name (e.g. "gpt-4o-mini")
    model: String,
    /// Maximum communities to enrich (skip the rest)
    max_communities: usize,
    /// Top N members per community to include in the prompt (by PageRank)
    top_members: usize,
    /// Batch size (communities per LLM call)
    batch_size: usize,
    /// Request timeout in seconds
    timeout_secs: u64,
}

impl LlmCommunityEnricher {
    /// Create a new LLM enricher with the given API configuration.
    pub fn new(api_base: String, api_key: String, model: String) -> Self {
        Self {
            client: reqwest::Client::new(),
            api_base,
            api_key,
            model,
            max_communities: 50,
            top_members: 10,
            batch_size: 5,
            timeout_secs: 30,
        }
    }

    /// Build the prompt for a batch of communities.
    fn build_prompt(
        &self,
        batch: &[(u32, &str, Vec<String>)], // (community_id, heuristic_label, top_members)
    ) -> String {
        let mut prompt = String::from(
            "Given these code communities detected by Louvain algorithm, suggest a short label (2-4 words) for each.\n\n",
        );

        for (id, heuristic, members) in batch {
            prompt.push_str(&format!(
                "Community {} (heuristic: \"{}\"): {}\n",
                id,
                heuristic,
                members.join(", ")
            ));
        }

        prompt.push_str("\nReply ONLY with a JSON object mapping community ID to label. Example: {\"0\": \"API Request Handling\", \"1\": \"Database Layer\"}");
        prompt
    }

    /// Select top N members of a community by PageRank.
    fn top_members_by_pagerank(
        &self,
        community: &CommunityInfo,
        metrics: &HashMap<String, NodeMetrics>,
    ) -> Vec<String> {
        let mut scored: Vec<(&String, f64)> = community
            .members
            .iter()
            .map(|m| (m, metrics.get(m).map(|n| n.pagerank).unwrap_or(0.0)))
            .collect();
        scored.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));
        scored
            .into_iter()
            .take(self.top_members)
            .map(|(m, _)| m.clone())
            .collect()
    }

    /// Call the LLM API and parse the response.
    async fn call_llm(&self, prompt: &str) -> Result<HashMap<String, String>> {
        let url = format!("{}/chat/completions", self.api_base);

        let body = serde_json::json!({
            "model": self.model,
            "messages": [
                {"role": "system", "content": "You are a code architecture analyst. Reply only with valid JSON."},
                {"role": "user", "content": prompt}
            ],
            "temperature": 0.3,
            "max_tokens": 500
        });

        let resp = self
            .client
            .post(&url)
            .header("Authorization", format!("Bearer {}", self.api_key))
            .header("Content-Type", "application/json")
            .timeout(std::time::Duration::from_secs(self.timeout_secs))
            .json(&body)
            .send()
            .await?;

        let status = resp.status();
        if !status.is_success() {
            let text = resp.text().await.unwrap_or_default();
            anyhow::bail!("LLM API returned {}: {}", status, text);
        }

        let json: serde_json::Value = resp.json().await?;
        let content = json["choices"][0]["message"]["content"]
            .as_str()
            .unwrap_or("{}");

        // Try to extract JSON from the response (may be wrapped in ```json blocks)
        let clean = content
            .trim()
            .trim_start_matches("```json")
            .trim_start_matches("```")
            .trim_end_matches("```")
            .trim();

        let parsed: HashMap<String, String> = serde_json::from_str(clean).unwrap_or_default();

        Ok(parsed)
    }
}

#[async_trait]
impl CommunityEnricher for LlmCommunityEnricher {
    async fn enrich_labels(
        &self,
        communities: &mut [CommunityInfo],
        _graph: &CodeGraph,
        metrics: &HashMap<String, NodeMetrics>,
    ) -> Result<()> {
        let to_enrich = communities.len().min(self.max_communities);

        // Prepare batches
        let mut batches: Vec<Vec<(usize, u32, String, Vec<String>)>> = Vec::new();
        let mut current_batch = Vec::new();

        for (idx, community) in communities.iter().enumerate().take(to_enrich) {
            // Skip tiny communities (1 member → label is obvious)
            if community.size <= 1 {
                continue;
            }

            let top = self.top_members_by_pagerank(community, metrics);
            current_batch.push((idx, community.id, community.label.clone(), top));

            if current_batch.len() >= self.batch_size {
                batches.push(std::mem::take(&mut current_batch));
            }
        }
        if !current_batch.is_empty() {
            batches.push(current_batch);
        }

        // Process each batch
        for batch in &batches {
            let prompt_data: Vec<(u32, &str, Vec<String>)> = batch
                .iter()
                .map(|(_, id, label, members)| (*id, label.as_str(), members.clone()))
                .collect();

            let prompt = self.build_prompt(&prompt_data);

            match self.call_llm(&prompt).await {
                Ok(labels) => {
                    for (idx, id, _, _) in batch {
                        let key = id.to_string();
                        if let Some(new_label) = labels.get(&key) {
                            if !new_label.is_empty() {
                                communities[*idx].label = new_label.clone();
                                communities[*idx].enriched_by = Some("llm".to_string());
                            }
                        }
                    }
                }
                Err(e) => {
                    tracing::warn!(
                        "LLM enrichment failed for batch, keeping heuristic labels: {}",
                        e
                    );
                    // Labels stay as heuristic (already set)
                }
            }
        }

        Ok(())
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::graph::models::{CodeEdge, CodeEdgeType, CodeNode, CodeNodeType};

    fn make_test_communities() -> (Vec<CommunityInfo>, CodeGraph, HashMap<String, NodeMetrics>) {
        let mut graph = CodeGraph::new();
        let mut metrics = HashMap::new();

        // Community 0: API files
        for name in &[
            "src/api/handlers.rs",
            "src/api/routes.rs",
            "src/api/middleware.rs",
        ] {
            graph.add_node(CodeNode {
                id: name.to_string(),
                node_type: CodeNodeType::File,
                path: Some(name.to_string()),
                name: name.to_string(),
                project_id: None,
            });
            metrics.insert(
                name.to_string(),
                NodeMetrics {
                    pagerank: 0.1,
                    community_id: 0,
                    ..Default::default()
                },
            );
        }

        // Community 1: Graph files
        for name in &["src/graph/algorithms.rs", "src/graph/models.rs"] {
            graph.add_node(CodeNode {
                id: name.to_string(),
                node_type: CodeNodeType::File,
                path: Some(name.to_string()),
                name: name.to_string(),
                project_id: None,
            });
            metrics.insert(
                name.to_string(),
                NodeMetrics {
                    pagerank: 0.2,
                    community_id: 1,
                    ..Default::default()
                },
            );
        }

        let communities = vec![
            CommunityInfo {
                id: 0,
                size: 3,
                members: vec![
                    "src/api/handlers.rs".to_string(),
                    "src/api/routes.rs".to_string(),
                    "src/api/middleware.rs".to_string(),
                ],
                label: "api".to_string(),
                cohesion: 0.9,
                enriched_by: Some("heuristic".to_string()),
            },
            CommunityInfo {
                id: 1,
                size: 2,
                members: vec![
                    "src/graph/algorithms.rs".to_string(),
                    "src/graph/models.rs".to_string(),
                ],
                label: "graph".to_string(),
                cohesion: 0.95,
                enriched_by: Some("heuristic".to_string()),
            },
        ];

        (communities, graph, metrics)
    }

    #[tokio::test]
    async fn test_noop_enricher_leaves_labels_unchanged() {
        let (mut communities, graph, metrics) = make_test_communities();
        let enricher = NoopCommunityEnricher;

        enricher
            .enrich_labels(&mut communities, &graph, &metrics)
            .await
            .unwrap();

        assert_eq!(communities[0].label, "api");
        assert_eq!(communities[1].label, "graph");
        assert_eq!(communities[0].enriched_by, Some("heuristic".to_string()));
        assert_eq!(communities[1].enriched_by, Some("heuristic".to_string()));
    }

    #[test]
    fn test_llm_enricher_build_prompt() {
        let enricher = LlmCommunityEnricher::new(
            "http://localhost:8080/v1".to_string(),
            "test-key".to_string(),
            "gpt-4o-mini".to_string(),
        );

        let batch = vec![
            (
                0u32,
                "api",
                vec![
                    "src/api/handlers.rs".to_string(),
                    "src/api/routes.rs".to_string(),
                ],
            ),
            (1u32, "graph", vec!["src/graph/algorithms.rs".to_string()]),
        ];

        let prompt = enricher.build_prompt(&batch);
        assert!(prompt.contains("Community 0"));
        assert!(prompt.contains("Community 1"));
        assert!(prompt.contains("src/api/handlers.rs"));
        assert!(prompt.contains("heuristic: \"api\""));
        assert!(prompt.contains("JSON"));
    }

    #[test]
    fn test_llm_enricher_top_members_by_pagerank() {
        let enricher = LlmCommunityEnricher::new(
            "http://localhost:8080/v1".to_string(),
            "test-key".to_string(),
            "gpt-4o-mini".to_string(),
        );

        let community = CommunityInfo {
            id: 0,
            size: 3,
            members: vec!["a".to_string(), "b".to_string(), "c".to_string()],
            label: "test".to_string(),
            cohesion: 0.0,
            enriched_by: None,
        };

        let mut metrics = HashMap::new();
        metrics.insert(
            "a".to_string(),
            NodeMetrics {
                pagerank: 0.1,
                ..Default::default()
            },
        );
        metrics.insert(
            "b".to_string(),
            NodeMetrics {
                pagerank: 0.5,
                ..Default::default()
            },
        );
        metrics.insert(
            "c".to_string(),
            NodeMetrics {
                pagerank: 0.3,
                ..Default::default()
            },
        );

        let top = enricher.top_members_by_pagerank(&community, &metrics);
        assert_eq!(top.len(), 3);
        assert_eq!(top[0], "b"); // highest PageRank first
        assert_eq!(top[1], "c");
        assert_eq!(top[2], "a");
    }
}
