//! # Pipeline Runner — Orchestrates pipeline execution
//!
//! Executes a pipeline generated by the composer, coordinating:
//! - Wave execution via WaveExecutor
//! - Quality gate checks between waves
//! - Progress tracking via ProgressOracle
//! - Regression detection via RegressionDetector
//! - Protocol state transitions

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::composer::{GateSpec, PipelineSpec};
use super::gates::{
    CargoCheckGate, CargoTestGate, CoverageGate, GateContext, GateResult, GateStatus,
    NpmTypeCheckGate, PrChecksGate, QualityGate,
};
use super::progress::{Checkpoint, ProgressOracle};
use super::regression::{ErrorCategory, ErrorSignature, RegressionDetector, StopReason};
use super::wave_executor::{WaveExecutor, WaveSpec, WaveStatus};

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

/// Configuration for a pipeline run.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PipelineConfig {
    /// Working directory for command execution.
    pub cwd: String,
    /// Project slug (for MCP calls).
    pub project_slug: Option<String>,
    /// Maximum retries per gate before marking it as failed.
    pub max_retries_per_gate: usize,
    /// Overall pipeline timeout in seconds.
    pub timeout_secs: u64,
    /// Stop on first gate failure.
    pub fail_fast: bool,
}

impl Default for PipelineConfig {
    fn default() -> Self {
        Self {
            cwd: ".".to_string(),
            project_slug: None,
            max_retries_per_gate: 2,
            timeout_secs: 3600,
            fail_fast: true,
        }
    }
}

// ---------------------------------------------------------------------------
// Status & event types
// ---------------------------------------------------------------------------

/// Status of a pipeline run.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum PipelineRunStatus {
    Running,
    Completed,
    Failed,
    /// Stopped by RegressionDetector.
    Stopped,
    Cancelled,
}

/// Event emitted during pipeline execution for real-time monitoring.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PipelineEvent {
    pub timestamp: DateTime<Utc>,
    pub event_type: PipelineEventType,
    pub message: String,
    pub metadata: HashMap<String, serde_json::Value>,
}

/// Types of pipeline events.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum PipelineEventType {
    PipelineStarted,
    WaveStarted,
    WaveCompleted,
    WaveFailed,
    GateStarted,
    GatePassed,
    GateFailed,
    GateSkipped,
    RegressionDetected,
    StagnationDetected,
    PipelineCompleted,
    PipelineFailed,
    PipelineStopped,
}

// ---------------------------------------------------------------------------
// Result
// ---------------------------------------------------------------------------

/// Result of a complete pipeline run.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PipelineRunResult {
    pub plan_id: Uuid,
    pub status: PipelineRunStatus,
    pub started_at: DateTime<Utc>,
    pub completed_at: DateTime<Utc>,
    pub duration_ms: u64,
    pub waves_completed: usize,
    pub waves_total: usize,
    pub gate_results: Vec<GateResult>,
    pub final_score: f64,
    pub stop_reason: Option<StopReason>,
    pub events: Vec<PipelineEvent>,
}

// ---------------------------------------------------------------------------
// Pipeline Runner
// ---------------------------------------------------------------------------

/// The Pipeline Runner — drives a composed pipeline through its stages.
pub struct PipelineRunner {
    config: PipelineConfig,
    oracle: ProgressOracle,
    detector: RegressionDetector,
    wave_executor: WaveExecutor,
    events: Vec<PipelineEvent>,
}

impl PipelineRunner {
    /// Create a new pipeline runner with the given configuration.
    pub fn new(config: PipelineConfig) -> Self {
        Self {
            oracle: ProgressOracle::with_defaults(),
            detector: RegressionDetector::default(),
            wave_executor: WaveExecutor::new(config.timeout_secs),
            events: Vec::new(),
            config,
        }
    }

    /// Execute a pipeline specification and return the result.
    ///
    /// The execution loop:
    /// 1. For each stage, run pre-gates, execute the wave, then run post-gates.
    /// 2. After all stages, run final gates.
    /// 3. Check the regression detector after each gate.
    /// 4. Track progress via the oracle.
    pub async fn run(&mut self, spec: &PipelineSpec) -> PipelineRunResult {
        let started_at = Utc::now();
        let mut gate_results = Vec::new();
        let mut waves_completed = 0usize;
        let waves_total = spec.stages.len();
        let mut status = PipelineRunStatus::Running;
        let mut stop_reason: Option<StopReason> = None;

        self.emit_event(
            PipelineEventType::PipelineStarted,
            &format!(
                "Starting pipeline '{}' with {} stages",
                spec.name, waves_total
            ),
            HashMap::new(),
        );

        let gate_context = GateContext {
            cwd: self.config.cwd.clone(),
            project_slug: self.config.project_slug.clone(),
            params: HashMap::new(),
        };

        // Execute each stage
        'stages: for stage in &spec.stages {
            // --- Pre-gates ---
            for gate_spec in &stage.pre_gates {
                let result = self.run_gate(gate_spec, &gate_context).await;
                let failed = result.status == GateStatus::Fail;
                gate_results.push(result);

                if failed && self.config.fail_fast {
                    status = PipelineRunStatus::Failed;
                    break 'stages;
                }

                // Check regression detector
                let detector_verdict = self.detector.should_stop();
                if detector_verdict != StopReason::Continue {
                    self.emit_stop_event(&detector_verdict);
                    stop_reason = Some(detector_verdict);
                    status = PipelineRunStatus::Stopped;
                    break 'stages;
                }
            }

            // --- Execute wave ---
            let wave_spec = WaveSpec {
                wave_number: stage.wave_number,
                plan_id: spec.plan_id,
                task_ids: stage.task_ids.clone(),
                cwd: self.config.cwd.clone(),
                project_slug: self.config.project_slug.clone(),
            };

            self.emit_event(
                PipelineEventType::WaveStarted,
                &format!(
                    "Starting wave {} ({} tasks)",
                    stage.wave_number,
                    stage.task_ids.len()
                ),
                {
                    let mut m = HashMap::new();
                    m.insert("wave_number".into(), serde_json::json!(stage.wave_number));
                    m
                },
            );

            let wave_result = self.wave_executor.execute(&wave_spec).await;

            match wave_result.overall_status {
                WaveStatus::Success => {
                    waves_completed += 1;
                    self.emit_event(
                        PipelineEventType::WaveCompleted,
                        &format!("Wave {} completed successfully", stage.wave_number),
                        HashMap::new(),
                    );
                }
                _ => {
                    self.emit_event(
                        PipelineEventType::WaveFailed,
                        &format!(
                            "Wave {} failed with status {:?}",
                            stage.wave_number, wave_result.overall_status
                        ),
                        HashMap::new(),
                    );
                    if self.config.fail_fast {
                        status = PipelineRunStatus::Failed;
                        break 'stages;
                    }
                }
            }

            // --- Post-gates ---
            for gate_spec in &stage.post_gates {
                let result = self.run_gate(gate_spec, &gate_context).await;
                let failed = result.status == GateStatus::Fail;
                gate_results.push(result);

                if failed && self.config.fail_fast {
                    status = PipelineRunStatus::Failed;
                    break 'stages;
                }

                // Check regression detector
                let detector_verdict = self.detector.should_stop();
                if detector_verdict != StopReason::Continue {
                    self.emit_stop_event(&detector_verdict);
                    stop_reason = Some(detector_verdict);
                    status = PipelineRunStatus::Stopped;
                    break 'stages;
                }
            }
        }

        // --- Final gates (only if still running) ---
        if status == PipelineRunStatus::Running {
            for gate_spec in &spec.final_gates {
                let result = self.run_gate(gate_spec, &gate_context).await;
                let failed = result.status == GateStatus::Fail;
                gate_results.push(result);

                if failed && self.config.fail_fast {
                    status = PipelineRunStatus::Failed;
                    break;
                }
            }
        }

        // Determine final status
        if status == PipelineRunStatus::Running {
            status = PipelineRunStatus::Completed;
        }

        // Compute final score from oracle
        let final_score = self.oracle.latest_score().map(|s| s.score).unwrap_or(0.0);

        // Emit final event
        match &status {
            PipelineRunStatus::Completed => {
                self.emit_event(
                    PipelineEventType::PipelineCompleted,
                    &format!(
                        "Pipeline '{}' completed — {}/{} waves, score {:.2}",
                        spec.name, waves_completed, waves_total, final_score
                    ),
                    HashMap::new(),
                );
            }
            PipelineRunStatus::Failed => {
                self.emit_event(
                    PipelineEventType::PipelineFailed,
                    &format!(
                        "Pipeline '{}' failed — {}/{} waves completed",
                        spec.name, waves_completed, waves_total
                    ),
                    HashMap::new(),
                );
            }
            PipelineRunStatus::Stopped => {
                self.emit_event(
                    PipelineEventType::PipelineStopped,
                    &format!("Pipeline '{}' stopped by regression detector", spec.name),
                    HashMap::new(),
                );
            }
            _ => {}
        }

        let completed_at = Utc::now();
        let duration_ms = (completed_at - started_at).num_milliseconds().max(0) as u64;

        PipelineRunResult {
            plan_id: spec.plan_id,
            status,
            started_at,
            completed_at,
            duration_ms,
            waves_completed,
            waves_total,
            gate_results,
            final_score,
            stop_reason,
            events: self.events.clone(),
        }
    }

    /// Run a single quality gate, recording results in the detector and oracle.
    async fn run_gate(&mut self, gate_spec: &GateSpec, context: &GateContext) -> GateResult {
        self.emit_event(
            PipelineEventType::GateStarted,
            &format!("Running gate '{}'", gate_spec.gate_type),
            {
                let mut m = HashMap::new();
                m.insert("gate_type".into(), serde_json::json!(gate_spec.gate_type));
                m
            },
        );

        let gate = create_gate(&gate_spec.gate_type, &gate_spec.params);
        let result = gate.check(context).await;

        // Emit event based on result
        match result.status {
            GateStatus::Pass => {
                self.emit_event(
                    PipelineEventType::GatePassed,
                    &format!("Gate '{}' passed: {}", gate_spec.gate_type, result.message),
                    HashMap::new(),
                );
            }
            GateStatus::Fail => {
                self.emit_event(
                    PipelineEventType::GateFailed,
                    &format!("Gate '{}' failed: {}", gate_spec.gate_type, result.message),
                    HashMap::new(),
                );

                // Record in regression detector
                let sig = ErrorSignature::from_message(
                    &result.message,
                    None,
                    None,
                    gate_type_to_error_category(&gate_spec.gate_type),
                );
                self.detector.record_error(sig);
            }
            GateStatus::Skip => {
                self.emit_event(
                    PipelineEventType::GateSkipped,
                    &format!("Gate '{}' skipped: {}", gate_spec.gate_type, result.message),
                    HashMap::new(),
                );
            }
            GateStatus::Error => {
                self.emit_event(
                    PipelineEventType::GateFailed,
                    &format!("Gate '{}' errored: {}", gate_spec.gate_type, result.message),
                    HashMap::new(),
                );

                let sig = ErrorSignature::from_message(
                    &result.message,
                    None,
                    None,
                    gate_type_to_error_category(&gate_spec.gate_type),
                );
                self.detector.record_error(sig);
            }
        }

        // Record checkpoint in oracle
        let error_count = result.metrics.get("error_count").copied().unwrap_or(0.0) as usize;
        let tests_passed = result.metrics.get("tests_passed").copied().unwrap_or(0.0) as usize;
        let tests_failed = result.metrics.get("tests_failed").copied().unwrap_or(0.0) as usize;
        let coverage = result.metrics.get("coverage_pct").copied().unwrap_or(0.0);

        let checkpoint = Checkpoint {
            seq: 0,
            tests_total: tests_passed + tests_failed,
            tests_passing: tests_passed,
            tests_failing: tests_failed,
            build_errors_count: error_count,
            coverage_pct: coverage,
            steps_completed: 0,
            steps_total: 0,
            warnings_count: result.metrics.get("warning_count").copied().unwrap_or(0.0) as usize,
            timestamp: Utc::now(),
        };
        self.oracle.record_checkpoint(checkpoint);

        result
    }

    /// Emit a pipeline event.
    fn emit_event(
        &mut self,
        event_type: PipelineEventType,
        message: &str,
        metadata: HashMap<String, serde_json::Value>,
    ) {
        self.events.push(PipelineEvent {
            timestamp: Utc::now(),
            event_type,
            message: message.to_string(),
            metadata,
        });
    }

    /// Emit the appropriate stop event for a regression detector verdict.
    fn emit_stop_event(&mut self, reason: &StopReason) {
        match reason {
            StopReason::Loop { seen_count, .. } => {
                self.emit_event(
                    PipelineEventType::RegressionDetected,
                    &format!("Loop detected: same error seen {seen_count} times"),
                    HashMap::new(),
                );
            }
            StopReason::Regression { test_name } => {
                self.emit_event(
                    PipelineEventType::RegressionDetected,
                    &format!("Regression detected: test '{test_name}' was passing, now failing"),
                    HashMap::new(),
                );
            }
            StopReason::Stagnation {
                iterations_without_progress,
            } => {
                self.emit_event(
                    PipelineEventType::StagnationDetected,
                    &format!(
                        "Stagnation detected: no progress over {iterations_without_progress} iterations"
                    ),
                    HashMap::new(),
                );
            }
            StopReason::Continue => {}
        }
    }
}

// ---------------------------------------------------------------------------
// Gate factory
// ---------------------------------------------------------------------------

/// Create a quality gate instance from a gate type string and parameters.
///
/// Supported gate types:
/// - `"cargo-check"` → [`CargoCheckGate`]
/// - `"cargo-test"` → [`CargoTestGate`]
/// - `"coverage"` → [`CoverageGate`] (reads `threshold` param)
/// - `"npm-typecheck"` → [`NpmTypeCheckGate`]
/// - `"pr-checks"` → [`PrChecksGate`]
///
/// Unknown gate types fall back to [`CargoCheckGate`] (a safe default that
/// will simply report compilation status).
pub fn create_gate(
    gate_type: &str,
    params: &HashMap<String, serde_json::Value>,
) -> Box<dyn QualityGate> {
    match gate_type {
        "cargo-check" => Box::new(CargoCheckGate),
        "cargo-test" => Box::new(CargoTestGate),
        "coverage" => {
            let threshold = params
                .get("threshold")
                .and_then(|v| v.as_f64())
                .unwrap_or(60.0);
            Box::new(CoverageGate { threshold })
        }
        "npm-typecheck" => Box::new(NpmTypeCheckGate),
        "pr-checks" => Box::new(PrChecksGate),
        _ => Box::new(CargoCheckGate), // safe fallback
    }
}

/// Map a gate type string to an [`ErrorCategory`] for the regression detector.
fn gate_type_to_error_category(gate_type: &str) -> ErrorCategory {
    match gate_type {
        "cargo-check" => ErrorCategory::Compile,
        "cargo-test" => ErrorCategory::Test,
        "coverage" => ErrorCategory::Coverage,
        "npm-typecheck" => ErrorCategory::Compile,
        "pr-checks" => ErrorCategory::Other,
        _ => ErrorCategory::Other,
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // -- PipelineConfig defaults --------------------------------------------

    #[test]
    fn config_defaults() {
        let config = PipelineConfig::default();
        assert_eq!(config.cwd, ".");
        assert!(config.project_slug.is_none());
        assert_eq!(config.max_retries_per_gate, 2);
        assert_eq!(config.timeout_secs, 3600);
        assert!(config.fail_fast);
    }

    #[test]
    fn config_serialization_roundtrip() {
        let config = PipelineConfig {
            cwd: "/tmp/project".to_string(),
            project_slug: Some("my-project".to_string()),
            max_retries_per_gate: 3,
            timeout_secs: 7200,
            fail_fast: false,
        };
        let json = serde_json::to_string(&config).unwrap();
        let back: PipelineConfig = serde_json::from_str(&json).unwrap();
        assert_eq!(back.cwd, "/tmp/project");
        assert_eq!(back.project_slug.as_deref(), Some("my-project"));
        assert_eq!(back.max_retries_per_gate, 3);
        assert_eq!(back.timeout_secs, 7200);
        assert!(!back.fail_fast);
    }

    // -- create_gate factory ------------------------------------------------

    #[test]
    fn create_gate_cargo_check() {
        let gate = create_gate("cargo-check", &HashMap::new());
        assert_eq!(gate.name(), "cargo-check");
    }

    #[test]
    fn create_gate_cargo_test() {
        let gate = create_gate("cargo-test", &HashMap::new());
        assert_eq!(gate.name(), "cargo-test");
    }

    #[test]
    fn create_gate_coverage_default_threshold() {
        let gate = create_gate("coverage", &HashMap::new());
        assert_eq!(gate.name(), "coverage");
    }

    #[test]
    fn create_gate_coverage_custom_threshold() {
        let mut params = HashMap::new();
        params.insert("threshold".into(), serde_json::json!(80.0));
        let gate = create_gate("coverage", &params);
        assert_eq!(gate.name(), "coverage");
    }

    #[test]
    fn create_gate_npm_typecheck() {
        let gate = create_gate("npm-typecheck", &HashMap::new());
        assert_eq!(gate.name(), "npm-typecheck");
    }

    #[test]
    fn create_gate_pr_checks() {
        let gate = create_gate("pr-checks", &HashMap::new());
        assert_eq!(gate.name(), "pr-checks");
    }

    #[test]
    fn create_gate_unknown_falls_back() {
        let gate = create_gate("unknown-gate", &HashMap::new());
        // Falls back to CargoCheckGate
        assert_eq!(gate.name(), "cargo-check");
    }

    // -- PipelineEvent construction -----------------------------------------

    #[test]
    fn pipeline_event_construction() {
        let event = PipelineEvent {
            timestamp: Utc::now(),
            event_type: PipelineEventType::PipelineStarted,
            message: "Pipeline started".to_string(),
            metadata: HashMap::new(),
        };
        assert_eq!(event.event_type, PipelineEventType::PipelineStarted);
        assert_eq!(event.message, "Pipeline started");
    }

    #[test]
    fn pipeline_event_serialization_roundtrip() {
        let mut metadata = HashMap::new();
        metadata.insert("wave".into(), serde_json::json!(1));

        let event = PipelineEvent {
            timestamp: Utc::now(),
            event_type: PipelineEventType::WaveCompleted,
            message: "Wave 1 done".to_string(),
            metadata,
        };

        let json = serde_json::to_string(&event).unwrap();
        let back: PipelineEvent = serde_json::from_str(&json).unwrap();
        assert_eq!(back.event_type, PipelineEventType::WaveCompleted);
        assert_eq!(back.message, "Wave 1 done");
        assert_eq!(back.metadata["wave"], serde_json::json!(1));
    }

    // -- PipelineRunResult serialization ------------------------------------

    #[test]
    fn pipeline_run_result_serialization() {
        let now = Utc::now();
        let result = PipelineRunResult {
            plan_id: Uuid::new_v4(),
            status: PipelineRunStatus::Completed,
            started_at: now,
            completed_at: now,
            duration_ms: 1234,
            waves_completed: 2,
            waves_total: 3,
            gate_results: vec![],
            final_score: 0.85,
            stop_reason: None,
            events: vec![],
        };

        let json = serde_json::to_string(&result).unwrap();
        let back: PipelineRunResult = serde_json::from_str(&json).unwrap();
        assert_eq!(back.status, PipelineRunStatus::Completed);
        assert_eq!(back.waves_completed, 2);
        assert_eq!(back.waves_total, 3);
        assert!((back.final_score - 0.85).abs() < f64::EPSILON);
        assert!(back.stop_reason.is_none());
    }

    #[test]
    fn pipeline_run_result_with_stop_reason() {
        let now = Utc::now();
        let result = PipelineRunResult {
            plan_id: Uuid::new_v4(),
            status: PipelineRunStatus::Stopped,
            started_at: now,
            completed_at: now,
            duration_ms: 500,
            waves_completed: 1,
            waves_total: 3,
            gate_results: vec![],
            final_score: 0.3,
            stop_reason: Some(StopReason::Stagnation {
                iterations_without_progress: 5,
            }),
            events: vec![],
        };

        let json = serde_json::to_string(&result).unwrap();
        let back: PipelineRunResult = serde_json::from_str(&json).unwrap();
        assert_eq!(back.status, PipelineRunStatus::Stopped);
        assert!(back.stop_reason.is_some());
    }

    // -- PipelineRunStatus --------------------------------------------------

    #[test]
    fn pipeline_run_status_roundtrip() {
        for status in [
            PipelineRunStatus::Running,
            PipelineRunStatus::Completed,
            PipelineRunStatus::Failed,
            PipelineRunStatus::Stopped,
            PipelineRunStatus::Cancelled,
        ] {
            let json = serde_json::to_string(&status).unwrap();
            let back: PipelineRunStatus = serde_json::from_str(&json).unwrap();
            assert_eq!(back, status);
        }
    }

    // -- PipelineEventType --------------------------------------------------

    #[test]
    fn pipeline_event_type_roundtrip() {
        for event_type in [
            PipelineEventType::PipelineStarted,
            PipelineEventType::WaveStarted,
            PipelineEventType::WaveCompleted,
            PipelineEventType::WaveFailed,
            PipelineEventType::GateStarted,
            PipelineEventType::GatePassed,
            PipelineEventType::GateFailed,
            PipelineEventType::GateSkipped,
            PipelineEventType::RegressionDetected,
            PipelineEventType::StagnationDetected,
            PipelineEventType::PipelineCompleted,
            PipelineEventType::PipelineFailed,
            PipelineEventType::PipelineStopped,
        ] {
            let json = serde_json::to_string(&event_type).unwrap();
            let back: PipelineEventType = serde_json::from_str(&json).unwrap();
            assert_eq!(back, event_type);
        }
    }

    // -- gate_type_to_error_category ----------------------------------------

    #[test]
    fn error_category_mapping() {
        assert_eq!(
            gate_type_to_error_category("cargo-check"),
            ErrorCategory::Compile
        );
        assert_eq!(
            gate_type_to_error_category("cargo-test"),
            ErrorCategory::Test
        );
        assert_eq!(
            gate_type_to_error_category("coverage"),
            ErrorCategory::Coverage
        );
        assert_eq!(
            gate_type_to_error_category("npm-typecheck"),
            ErrorCategory::Compile
        );
        assert_eq!(
            gate_type_to_error_category("pr-checks"),
            ErrorCategory::Other
        );
        assert_eq!(gate_type_to_error_category("unknown"), ErrorCategory::Other);
    }
}
