//! InferenceEngine — real-time neural routing inference pipeline.
//!
//! Pipeline:
//! 1. Receive query (embedding already computed upstream)
//! 2. Optionally encode graph state via GNN (cached)
//! 3. Assemble state: [query_embedding(256d) || graph_embedding(256d)] = 512d
//! 4. Run Decision Transformer with configurable RTG target
//! 5. Decode action sequence via ActionCodebook
//! 6. Return Vec<PlannedAction> with confidence + OOD flags
//!
//! Latency budget: <15ms warm / <60ms cold.

use std::collections::HashSet;
use std::sync::Arc;
use std::time::Instant;

use candle_core::{DType, Device, Tensor};
use candle_nn::{VarBuilder, VarMap};
use serde::Serialize;
use tracing;

use neural_routing_gnn::GnnEncoder;
use neural_routing_policy::dataset::{QUERY_DIM, STATE_DIM};
use neural_routing_policy::{ActionCodebook, ActionDecoder, DecisionTransformer, DecodeResult};

// ---------------------------------------------------------------------------
// PlannedAction — output of the inference pipeline
// ---------------------------------------------------------------------------

/// A single planned MCP action with confidence metadata.
#[derive(Debug, Clone, Serialize)]
pub struct PlannedAction {
    /// MCP tool name (e.g., "code", "note", "task").
    pub tool: String,
    /// MCP action name (e.g., "search", "get_context", "create").
    pub action: String,
    /// Optional parameter template (hints for common params).
    pub param_template: Option<String>,
    /// Confidence score for this action (cosine similarity to codebook entry).
    pub confidence: f32,
    /// Historical average reward for this action type.
    pub estimated_reward: f32,
    /// Whether this action is out-of-distribution (low confidence).
    pub is_ood: bool,
    /// Step index in the predicted route (0-based).
    pub step: usize,
}

/// Result of the full inference pipeline.
#[derive(Debug, Clone, Serialize)]
pub struct InferenceResult {
    /// Predicted sequence of actions.
    pub actions: Vec<PlannedAction>,
    /// Overall confidence (geometric mean of per-action confidence).
    pub overall_confidence: f32,
    /// Whether any action was flagged as OOD.
    pub has_ood_actions: bool,
    /// Pipeline latency in microseconds.
    pub latency_us: u64,
    /// RTG target used for this inference.
    pub rtg_target: f32,
    /// Whether this was generated by the policy net (vs fallback).
    pub source: InferenceSource,
}

/// Source of the inference result.
#[derive(Debug, Clone, Copy, PartialEq, Serialize)]
pub enum InferenceSource {
    /// Generated by the Decision Transformer policy net.
    PolicyNet,
    /// Fell back to the NN Router (no policy net loaded).
    Fallback,
}

// ---------------------------------------------------------------------------
// InferenceEngine
// ---------------------------------------------------------------------------

/// Configuration for the InferenceEngine.
#[derive(Debug, Clone)]
pub struct InferenceEngineConfig {
    /// RTG target for the Decision Transformer.
    /// Default: 0.8 (p90 of historical rewards, configurable).
    pub rtg_target: f32,
    /// Maximum number of steps to generate.
    pub max_steps: usize,
    /// OOD confidence threshold: below this, flag as OOD.
    pub ood_threshold: f32,
    /// Device for inference (CPU).
    pub device: Device,
}

impl Default for InferenceEngineConfig {
    fn default() -> Self {
        Self {
            rtg_target: 0.8,
            max_steps: 8,
            ood_threshold: 0.6,
            device: Device::Cpu,
        }
    }
}

/// InferenceEngine — orchestrates the full neural routing pipeline.
///
/// Combines:
/// - GNN encoder (optional, for graph state)
/// - Decision Transformer (policy net)
/// - Action Codebook (decoder)
/// - OOD detection
///
/// Thread-safe: all mutable state is behind Arc or atomic.
pub struct InferenceEngine {
    /// Decision Transformer model.
    transformer: Option<DecisionTransformer>,
    /// VarMap holding the model weights (kept alive for the lifetime of the model).
    _varmap: Option<VarMap>,
    /// GNN encoder for graph state embedding (optional).
    gnn_encoder: Option<Arc<dyn GnnEncoder>>,
    /// Action codebook for decoding predicted vectors.
    codebook: Option<ActionCodebook>,
    /// Engine configuration.
    config: InferenceEngineConfig,
}

impl InferenceEngine {
    /// Create a new InferenceEngine without any model loaded.
    ///
    /// Call `load_model()` to load a checkpoint, or use the engine as a
    /// fallback-only router (always returns `InferenceSource::Fallback`).
    pub fn new(config: InferenceEngineConfig) -> Self {
        Self {
            transformer: None,
            _varmap: None,
            gnn_encoder: None,
            codebook: None,
            config,
        }
    }

    /// Load a Decision Transformer model with random weights (for testing).
    ///
    /// In production, use `load_checkpoint()` to load trained weights.
    pub fn load_random_model(&mut self) -> Result<(), InferenceError> {
        let varmap = VarMap::new();
        let vb = VarBuilder::from_varmap(&varmap, DType::F32, &self.config.device);

        let dt_config = neural_routing_policy::transformer::DecisionTransformerConfig {
            max_timesteps: self.config.max_steps.max(32),
            ..Default::default()
        };

        let transformer = DecisionTransformer::new(dt_config, vb)
            .map_err(|e| InferenceError::ModelLoad(format!("Failed to create DT: {}", e)))?;

        self.transformer = Some(transformer);
        self._varmap = Some(varmap);
        Ok(())
    }

    /// Load a trained Decision Transformer from a safetensors checkpoint.
    ///
    /// The checkpoint must have been saved with matching parameter names
    /// (same as VarMap key names from the DT constructor).
    pub fn load_checkpoint(&mut self, checkpoint_path: &str) -> Result<(), InferenceError> {
        // Load tensors from safetensors file
        let tensors = candle_core::safetensors::load(checkpoint_path, &self.config.device)
            .map_err(|e| InferenceError::ModelLoad(format!("Failed to load checkpoint: {}", e)))?;

        // Build VarBuilder from loaded tensors
        let vb = VarBuilder::from_tensors(tensors, DType::F32, &self.config.device);

        let dt_config = neural_routing_policy::transformer::DecisionTransformerConfig {
            max_timesteps: self.config.max_steps.max(32),
            ..Default::default()
        };

        let transformer = DecisionTransformer::new(dt_config, vb)
            .map_err(|e| InferenceError::ModelLoad(format!("Failed to create DT: {}", e)))?;

        tracing::info!(
            checkpoint = checkpoint_path,
            "Loaded Decision Transformer checkpoint"
        );

        self.transformer = Some(transformer);
        self._varmap = None; // Not needed when using from_tensors
        Ok(())
    }

    /// Set the GNN encoder for graph state embedding.
    pub fn set_gnn_encoder(&mut self, encoder: Arc<dyn GnnEncoder>) {
        self.gnn_encoder = Some(encoder);
    }

    /// Set the action codebook for decoding.
    pub fn set_codebook(&mut self, codebook: ActionCodebook) {
        self.codebook = Some(codebook);
    }

    /// Update the RTG target at runtime.
    pub fn set_rtg_target(&mut self, rtg_target: f32) {
        self.config.rtg_target = rtg_target;
    }

    /// Get the current RTG target.
    pub fn rtg_target(&self) -> f32 {
        self.config.rtg_target
    }

    /// Check if a model is loaded and ready for inference.
    pub fn is_ready(&self) -> bool {
        self.transformer.is_some() && self.codebook.is_some()
    }

    /// Run the full inference pipeline.
    ///
    /// - `query_embedding`: 256d query embedding (from Voyage or similar).
    /// - `graph_embedding`: Optional 256d graph state embedding (from GNN).
    ///   If None, uses a zero vector (NN-only mode).
    /// - `available_tools`: Optional filter — only decode actions using these tools.
    ///
    /// Returns an `InferenceResult` with the predicted route.
    pub fn infer(
        &self,
        query_embedding: &[f32],
        graph_embedding: Option<&[f32]>,
        available_tools: Option<&[String]>,
    ) -> Result<InferenceResult, InferenceError> {
        let start = Instant::now();

        // Validate input dimensions
        if query_embedding.len() != QUERY_DIM {
            return Err(InferenceError::InvalidInput(format!(
                "query_embedding must be {}d, got {}d",
                QUERY_DIM,
                query_embedding.len()
            )));
        }

        // Check if model is loaded
        let transformer = match &self.transformer {
            Some(t) => t,
            None => {
                return Ok(InferenceResult {
                    actions: vec![],
                    overall_confidence: 0.0,
                    has_ood_actions: false,
                    latency_us: start.elapsed().as_micros() as u64,
                    rtg_target: self.config.rtg_target,
                    source: InferenceSource::Fallback,
                });
            }
        };

        let codebook = match &self.codebook {
            Some(c) => c,
            None => {
                return Err(InferenceError::NoCodebook);
            }
        };

        // Build state vector: [query_embedding(256d) || graph_embedding(256d)] = 512d
        const ZERO_GRAPH_EMB: [f32; QUERY_DIM] = [0.0; QUERY_DIM];
        let graph_emb = graph_embedding.unwrap_or(&ZERO_GRAPH_EMB);
        let mut state_vec = Vec::with_capacity(STATE_DIM);
        state_vec.extend_from_slice(query_embedding);
        if graph_emb.len() >= QUERY_DIM {
            state_vec.extend_from_slice(&graph_emb[..QUERY_DIM]);
        } else {
            state_vec.extend_from_slice(graph_emb);
            state_vec.resize(STATE_DIM, 0.0);
        }

        // Convert to tensor
        let initial_state =
            Tensor::from_vec(state_vec, STATE_DIM, &self.config.device).map_err(|e| {
                InferenceError::Inference(format!("Failed to create state tensor: {}", e))
            })?;

        // Run autoregressive generation
        let action_tensors = transformer
            .generate(
                self.config.rtg_target,
                &initial_state,
                self.config.max_steps,
            )
            .map_err(|e| InferenceError::Inference(format!("DT generation failed: {}", e)))?;

        // Decode action tensors to MCP actions
        let decoder = if let Some(tools) = available_tools {
            let available_set: HashSet<String> = tools.iter().cloned().collect();
            ActionDecoder::new(codebook).with_available_actions(available_set)
        } else {
            ActionDecoder::new(codebook)
        };

        let mut actions = Vec::with_capacity(action_tensors.len());
        let mut has_ood = false;
        let mut confidence_product = 1.0f32;

        for (step, action_tensor) in action_tensors.iter().enumerate() {
            // Convert tensor to Vec<f32>
            let action_vec: Vec<f32> = action_tensor.to_vec1().map_err(|e| {
                InferenceError::Inference(format!("Failed to read action tensor: {}", e))
            })?;

            // Decode via codebook
            match decoder.decode(&action_vec) {
                DecodeResult::Action(decoded) => {
                    confidence_product *= decoded.confidence;
                    actions.push(PlannedAction {
                        tool: decoded.tool,
                        action: decoded.action,
                        param_template: decoded.param_template,
                        confidence: decoded.confidence,
                        estimated_reward: decoded.avg_reward,
                        is_ood: false,
                        step,
                    });
                }
                DecodeResult::Ood {
                    best_similarity,
                    best_guess,
                    ..
                } => {
                    has_ood = true;
                    confidence_product *= best_similarity;
                    actions.push(PlannedAction {
                        tool: best_guess.tool,
                        action: best_guess.action,
                        param_template: best_guess.param_template,
                        confidence: best_similarity,
                        estimated_reward: best_guess.avg_reward,
                        is_ood: true,
                        step,
                    });
                }
                DecodeResult::NoCodebook => {
                    // Skip this step — codebook issue
                    tracing::warn!(step, "No codebook match for step, skipping");
                }
            }
        }

        // Compute overall confidence (geometric mean)
        let overall_confidence = if !actions.is_empty() {
            confidence_product.powf(1.0 / actions.len() as f32)
        } else {
            0.0
        };

        let latency_us = start.elapsed().as_micros() as u64;

        tracing::debug!(
            actions = actions.len(),
            overall_confidence = %format!("{:.3}", overall_confidence),
            has_ood = has_ood,
            latency_us = latency_us,
            "InferenceEngine: generated route"
        );

        Ok(InferenceResult {
            actions,
            overall_confidence,
            has_ood_actions: has_ood,
            latency_us,
            rtg_target: self.config.rtg_target,
            source: InferenceSource::PolicyNet,
        })
    }
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

/// Errors from the inference pipeline.
#[derive(Debug, thiserror::Error)]
pub enum InferenceError {
    #[error("Model load error: {0}")]
    ModelLoad(String),

    #[error("Inference error: {0}")]
    Inference(String),

    #[error("Invalid input: {0}")]
    InvalidInput(String),

    #[error("No codebook loaded")]
    NoCodebook,
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use neural_routing_policy::CodebookBuilder;

    fn make_embedding(seed: f32) -> Vec<f32> {
        (0..QUERY_DIM)
            .map(|i| ((i as f32 + seed) * 0.1).sin())
            .collect()
    }

    fn make_codebook() -> ActionCodebook {
        let mut builder = CodebookBuilder::new();
        let actions = [
            ("note", "create", 1.0),
            ("note", "search_semantic", 2.0),
            ("task", "update", 3.0),
            ("code", "search", 4.0),
            ("code", "analyze_impact", 5.0),
            ("plan", "create", 6.0),
            ("step", "update", 7.0),
        ];

        for (i, (tool, action, seed)) in actions.iter().enumerate() {
            let emb = make_embedding(*seed * 50.0);
            for _ in 0..10 {
                builder.observe(tool, action, &emb, 0.5 + i as f32 * 0.1);
            }
        }

        let mut codebook = builder.build();
        codebook.ood_threshold = 0.5;
        codebook
    }

    #[test]
    fn test_new_engine() {
        let engine = InferenceEngine::new(InferenceEngineConfig::default());
        assert!(!engine.is_ready());
        assert_eq!(engine.rtg_target(), 0.8);
    }

    #[test]
    fn test_infer_without_model_returns_fallback() {
        let engine = InferenceEngine::new(InferenceEngineConfig::default());
        let query = make_embedding(1.0);

        let result = engine.infer(&query, None, None).unwrap();
        assert_eq!(result.source, InferenceSource::Fallback);
        assert!(result.actions.is_empty());
    }

    #[test]
    fn test_infer_invalid_query_dim() {
        let engine = InferenceEngine::new(InferenceEngineConfig::default());
        let query = vec![1.0f32; 10]; // Wrong dimension

        let result = engine.infer(&query, None, None);
        assert!(result.is_err());
        match result {
            Err(InferenceError::InvalidInput(_)) => {}
            other => panic!("Expected InvalidInput, got {:?}", other),
        }
    }

    #[test]
    fn test_infer_no_codebook() {
        let mut engine = InferenceEngine::new(InferenceEngineConfig {
            max_steps: 4,
            ..Default::default()
        });
        engine.load_random_model().unwrap();
        // No codebook set

        let query = make_embedding(1.0);
        let result = engine.infer(&query, None, None);
        assert!(result.is_err());
        match result {
            Err(InferenceError::NoCodebook) => {}
            other => panic!("Expected NoCodebook, got {:?}", other),
        }
    }

    #[test]
    fn test_infer_with_random_model() {
        let mut engine = InferenceEngine::new(InferenceEngineConfig {
            max_steps: 4,
            rtg_target: 0.8,
            ..Default::default()
        });
        engine.load_random_model().unwrap();
        engine.set_codebook(make_codebook());

        assert!(engine.is_ready());

        let query = make_embedding(1.0);
        let result = engine.infer(&query, None, None).unwrap();

        assert_eq!(result.source, InferenceSource::PolicyNet);
        assert!(!result.actions.is_empty());
        assert!(result.actions.len() <= 4);
        assert_eq!(result.rtg_target, 0.8);
        assert!(result.latency_us > 0);

        // Each action should have valid fields
        for (i, action) in result.actions.iter().enumerate() {
            assert!(!action.tool.is_empty());
            assert!(!action.action.is_empty());
            assert_eq!(action.step, i);
            assert!(action.confidence > 0.0);
        }
    }

    #[test]
    fn test_infer_with_graph_embedding() {
        let mut engine = InferenceEngine::new(InferenceEngineConfig {
            max_steps: 3,
            ..Default::default()
        });
        engine.load_random_model().unwrap();
        engine.set_codebook(make_codebook());

        let query = make_embedding(1.0);
        let graph_emb = make_embedding(42.0);

        let result = engine.infer(&query, Some(&graph_emb), None).unwrap();
        assert_eq!(result.source, InferenceSource::PolicyNet);
        assert!(!result.actions.is_empty());
    }

    #[test]
    fn test_infer_with_tool_filter() {
        let mut engine = InferenceEngine::new(InferenceEngineConfig {
            max_steps: 4,
            ..Default::default()
        });
        engine.load_random_model().unwrap();
        engine.set_codebook(make_codebook());

        let query = make_embedding(1.0);
        let tools = vec!["code.search".to_string(), "note.create".to_string()];

        let result = engine.infer(&query, None, Some(&tools)).unwrap();
        assert_eq!(result.source, InferenceSource::PolicyNet);

        // All decoded actions should be from the filter set (or OOD)
        for action in &result.actions {
            let key = format!("{}.{}", action.tool, action.action);
            assert!(
                tools.contains(&key) || action.is_ood,
                "Action {} should be in filter or OOD",
                key
            );
        }
    }

    #[test]
    fn test_set_rtg_target() {
        let mut engine = InferenceEngine::new(InferenceEngineConfig::default());
        assert_eq!(engine.rtg_target(), 0.8);

        engine.set_rtg_target(0.95);
        assert_eq!(engine.rtg_target(), 0.95);
    }

    #[test]
    fn test_infer_latency_reasonable() {
        // With a random model and small max_steps, inference should be fast
        let mut engine = InferenceEngine::new(InferenceEngineConfig {
            max_steps: 4,
            ..Default::default()
        });
        engine.load_random_model().unwrap();
        engine.set_codebook(make_codebook());

        let query = make_embedding(1.0);

        // Warm up
        let _ = engine.infer(&query, None, None);

        // Measure
        let start = Instant::now();
        let iterations = 5;
        for _ in 0..iterations {
            let _ = engine.infer(&query, None, None);
        }
        let avg_us = start.elapsed().as_micros() / iterations as u128;

        eprintln!("InferenceEngine avg latency: {}μs ({} steps)", avg_us, 4);

        // In debug mode, allow generous budget. Release should be <15ms.
        assert!(
            avg_us < 5_000_000, // 5 seconds in debug
            "Average latency {}μs is too high",
            avg_us
        );
    }

    #[test]
    fn test_different_rtg_produces_different_routes() {
        let mut engine = InferenceEngine::new(InferenceEngineConfig {
            max_steps: 4,
            ..Default::default()
        });
        engine.load_random_model().unwrap();
        engine.set_codebook(make_codebook());

        let query = make_embedding(1.0);

        engine.set_rtg_target(0.1);
        let result_low = engine.infer(&query, None, None).unwrap();

        engine.set_rtg_target(0.99);
        let result_high = engine.infer(&query, None, None).unwrap();

        // With different RTG targets, at least confidence values should differ
        // (actions may or may not differ depending on random weights)
        let conf_low: f32 = result_low.actions.iter().map(|a| a.confidence).sum();
        let conf_high: f32 = result_high.actions.iter().map(|a| a.confidence).sum();

        // They should produce some result
        assert!(!result_low.actions.is_empty());
        assert!(!result_high.actions.is_empty());

        eprintln!(
            "RTG 0.1 → {} actions (conf sum {:.3}), RTG 0.99 → {} actions (conf sum {:.3})",
            result_low.actions.len(),
            conf_low,
            result_high.actions.len(),
            conf_high
        );
    }
}
